class Food {
  String image, name, Description1, calaries, description2,time;
  int price,rating;

  Food({required this.time,required this.rating,required this.image, required this.name, required this.Description1, required this.calaries, required this.price,
      required this.description2});

  static List<Food> listOfFood = [
    Food(
        image: 'assets/image/fries.png',
        name:'Fries',
        Description1:'Crispy and tasty!',
        calaries:'160',
        time: '20-30 min',
        price:2,
        rating: 4,
        description2:'French fries are long, thin pieces of potato fried in oil or fat. The French fries were thin and crispy. To cook the French fries, put them into a deep pan of oil. Peel the potatoes and cut them into French fries.'),
    Food(
        image: 'assets/image/burger.png',
        name:'Cheesy Burger',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal1.png',
        name:'Combo deal 1',
        Description1:'Cripy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal2.png',
        name:'Deal 2',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: "20-30 min",
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/fries.png',
        name:'Fries',
        Description1:'Crispy and tasty!',
        calaries:'160',
        time: '20-30 min',
        price:2,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/burger.png',
        name:'Cheesy Burger',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal1.png',
        name:'Combo deal 1',
        Description1:'Cripy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal2.png',
        name:'Deal 2',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/fries.png',
        name:'Fries',
        Description1:'Crispy and tasty!',
        calaries:'160',
        time: '20-30 min',
        price:2,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/burger.png',
        name:'Cheesy Burger',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal1.png',
        name:'Combo deal 1',
        Description1:'Cripy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
    Food(
        image: 'assets/image/deal2.png',
        name:'Deal 2',
        Description1:'Cheesy and Delicious!',
        calaries:'200',
        time: '20-30 min',
        price:3,
        rating: 4,
        description2:'description'),
  ];
}
